# Generated by Django 5.1.2 on 2024-11-07 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='slot_available',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='roomtransfer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_room', to='app_core.rooms'),
        ),
    ]
